CREATE TABLE [dbo].[CarrierLoadTender]  
(
    [Id] INT NOT NULL PRIMARY KEY, 
    [Status] NVARCHAR(50) NOT NULL,
    [AckStatus] NVARCHAR(50) NULL,
    [TrackStatus] NVARCHAR(50) NULL,
    [TrackStatus_Updated] DATETIME NULL,
    [CustomerId] INT NOT NULL,
    [InboundEDIId] INT NOT NULL,
    [DocumentDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [CarrierCode] NVARCHAR(255) NULL,
    [ShipmentId] NVARCHAR(255) NULL,
    [Purpose] NVARCHAR(255) NULL,
    [ReferenceNo] NVARCHAR(255) NULL,
    [EquipmentNo] NVARCHAR(255) NULL,
    [BillToParty] NVARCHAR(255) NULL,
    [Weight] NVARCHAR(255) NULL,
    [WeightUnitCode] NVARCHAR(255) NULL,
    [TotalUnits] NVARCHAR(255) NULL,
    [TotalUnitsCode] NVARCHAR(255) NULL,
    [ShipperNo] NVARCHAR(255) NULL,
    [PickupDate] NVARCHAR(255) NULL,
    [PickupTime] NVARCHAR(255) NULL,
    [DeliverDate] NVARCHAR(255) NULL,
    [DeliverTime] NVARCHAR(255) NULL,
    [ShipFromName] NVARCHAR(255) NULL,
    [ShipFromCode] NVARCHAR(255) NULL,
    [ShipFromAddress] NVARCHAR(255) NULL,
    [ShipFromCity] NVARCHAR(255) NULL,
    [ShipFromState] NVARCHAR(255) NULL,
    [ShipFromZip] NVARCHAR(255) NULL,
    [ShipFromCountry] NVARCHAR(255) NULL,
    [ConsigneeName] NVARCHAR(255) NULL,
    [ConsigneeCode] NVARCHAR(255) NULL,
    [ConsigneeAddress] NVARCHAR(255) NULL,
    [ConsigneeCity] NVARCHAR(255) NULL,
    [ConsigneeState] NVARCHAR(255) NULL,
    [ConsigneeZip] NVARCHAR(255) NULL,
    [ConsigneeCountry] NVARCHAR(255) NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [CreatedBy] INT NOT NULL,
    [LastTrackStatus] NVARCHAR(100) NULL
)
