CREATE TABLE [dbo].[CustomerProductCatalogPrices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerID] [varchar](500) NOT NULL,
	[ItemId] [varchar](250) NOT NULL,
	[ProductID] [varchar](500) NOT NULL,
	[Status] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]