IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'OrdersLogs')
BEGIN
	CREATE TABLE [dbo].[OrdersLogs](
		[OLId] [int] IDENTITY(1,1) NOT NULL,
		[ActionType] [varchar](10) NOT NULL,
		[Id] [int] NOT NULL,
		[Status] [varchar](50) NOT NULL,
		[CustomerId] [int] NOT NULL,
		[InboundEDIId] [int] NULL,
		[OrderDate] [datetime] NOT NULL,
		[OrderNumber] [varchar](50) NULL,
		[VendorNumber] [varchar](50) NULL,
		[OrderType] [varchar](50) NULL,
		[ReferenceNo] [varchar](50) NULL,
		[CustomerOrderNo] [varchar](50) NULL,
		[ExternalId] [varchar](50) NULL,
		[ShippingMethod] [nvarchar](250) NULL,
		[ShipToId] [nvarchar](250) NULL,
		[ShipToName] [nvarchar](250) NULL,
		[ShipToAddress1] [nvarchar](250) NULL,
		[ShipToAddress2] [nvarchar](250) NULL,
		[ShipToCity] [nvarchar](250) NULL,
		[ShipToState] [nvarchar](50) NULL,
		[ShipToZip] [nvarchar](50) NULL,
		[ShipToCountry] [nvarchar](250) NULL,
		[ShipToEmail] [nvarchar](50) NULL,
		[ShipToPhone] [nvarchar](50) NULL,
		[BillToId] [nvarchar](250) NULL,
		[BillToName] [nvarchar](250) NULL,
		[BillToAddress1] [nvarchar](250) NULL,
		[BillToAddress2] [nvarchar](250) NULL,
		[BillToCity] [nvarchar](250) NULL,
		[BillToState] [nvarchar](50) NULL,
		[BillToZip] [nvarchar](50) NULL,
		[BillToCountry] [nvarchar](250) NULL,
		[BillToEmail] [nvarchar](50) NULL,
		[BillToPhone] [nvarchar](50) NULL,
		[BuyerId] [nvarchar](250) NULL,
		[BuyerName] [nvarchar](250) NULL,
		[BuyerAddress1] [nvarchar](250) NULL,
		[BuyerAddress2] [nvarchar](250) NULL,
		[BuyerCity] [nvarchar](250) NULL,
		[BuyerState] [nvarchar](50) NULL,
		[BuyerZip] [nvarchar](50) NULL,
		[BuyerCountry] [nvarchar](250) NULL,
		[BuyerEmail] [nvarchar](50) NULL,
		[BuyerPhone] [nvarchar](50) NULL,
		[IsStoreOrder] [bit] NOT NULL,
		[CreatedDate] [datetime] NOT NULL,
		[CreatedBy] [int] NOT NULL
		)
	END
GO
