CREATE TABLE [dbo].[SCSInventoryFeed_TAR6266P_Log]
(
    [LogID]            BIGINT        IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [BatchID]          NVARCHAR(500) NOT NULL,
    [LogType]          VARCHAR(20)   NOT NULL,
    [CustomerID]       VARCHAR(50)   NULL,
    [ItemId]           VARCHAR(50)   NULL,
    [CustomerItemCode] VARCHAR(50)   NULL,
    [ETA_Date]         NVARCHAR(30)  NULL,
    [ETA_Qty]          INT           NULL,
    [Total_ATS]        INT           NULL,
    [ATS_L10]          INT           NULL,
    [ATS_L21]          INT           NULL,
    [ATS_L28]          INT           NULL,
    [ATS_L29]          INT           NULL,
    [ATS_L30]          INT           NULL,
    [ATS_L34]          INT           NULL,
    [ATS_L35]          INT           NULL,
    [ATS_L36]          INT           NULL,
    [ATS_L37]          INT           NULL,
    [ATS_L40]          INT           NULL,
    [ATS_L41]          INT           NULL,
    [ATS_L55]          INT           NULL,
    [ATS_L56]          INT           NULL,
    [ATS_L57]          INT           NULL,
    [ATS_L60]          INT           NULL,
    [ATS_L65]          INT           NULL,
    [ATS_L70]          INT           NULL,
    [ATS_L91]          INT           NULL,
    [Status]           VARCHAR(20)   NULL,
    [LogDate]          DATETIME      NOT NULL DEFAULT GETDATE()
)
